---
  name: run app and test
  on: [push]
  jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - name: Snyk
         uses: snyk/actions/node@master
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
       - name: Set up Node.js environment
         uses: actions/setup-node@v4
         with:
           cache: 'npm'
       - name: make setup
         run: make setup
       - name: make test
         run: make test
       - name: make lint
         run: make lint
  